export default [
    { label: 'ISO/GET', width: 'label', group: true },

    { name: 'Esc', code: 'KC_ESC', keys: 'esc' },
    { width: 1000 },
    { name: 'F1', code: 'KC_F1', keys: 'f1' },
    { name: 'F2', code: 'KC_F2', keys: 'f2' },
    { name: 'F3', code: 'KC_F3', keys: 'f3' },
    { name: 'F4', code: 'KC_F4', keys: 'f4' },
    { width: 500 },
    { name: 'F5', code: 'KC_F5', keys: 'f5' },
    { name: 'F6', code: 'KC_F6', keys: 'f6' },
    { name: 'F7', code: 'KC_F7', keys: 'f7' },
    { name: 'F8', code: 'KC_F8', keys: 'f8' },
    { width: 500 },
    { name: 'F9', code: 'KC_F9', keys: 'f9' },
    { name: 'F10', code: 'KC_F10', keys: 'f10' },
    { name: 'F11', code: 'KC_F11', keys: 'f11' },
    { name: 'F12', code: 'KC_F12', keys: 'f12' },
    { width: 250 },
    { name: 'Print Screen', code: 'KC_PSCR' },
    { name: 'Scroll Lock', code: 'KC_SLCK' },
    { name: 'Pause', code: 'KC_PAUS' },
    { width: 0 },

    { name: '°\n^', code: 'DE_CIRC', keys: '^' },
    { name: '!\n1', code: 'DE_1', keys: '1' },
    { name: '"\n2', code: 'DE_2', keys: '2' },
    { name: '§\n3', code: 'DE_3', keys: '3' },
    { name: '$\n4', code: 'DE_4', keys: '4' },
    { name: '%\n5', code: 'DE_5', keys: '5' },
    { name: '&\n6', code: 'DE_6', keys: '6' },
    { name: '/\n7', code: 'DE_7', keys: '7' },
    { name: '(\n8', code: 'DE_8', keys: '8' },
    { name: ')\n9', code: 'DE_9', keys: '9' },
    { name: '=\n0', code: 'DE_0', keys: '0' },
    { name: '?\nß', code: 'DE_SS', keys: 'ß' },
    { name: '`\n´', code: 'DE_ACUT', keys: '´' },
    { name: 'Back Space', code: 'KC_BSPC', keys: 'backspace', width: 500 },
    { width: 250 },
    { name: 'Insert', code: 'KC_INS', keys: 'insert' },
    { name: 'Home', code: 'KC_HOME', keys: 'home' },
    { name: 'Page Up', code: 'KC_PGUP', keys: 'pageup' },
    { width: 250 },
    { name: 'Num Lock', code: 'KC_NLCK', keys: 'num' },
    { name: '/', code: 'KC_PSLS', keys: 'num_divide' },
    { name: '*', code: 'KC_PAST', keys: 'num_multiply' },
    { name: '-', code: 'KC_PMNS', keys: 'num_subtract' },
    { width: 0 },

    { name: 'Tab', code: 'KC_TAB', keys: 'tab', width: 1500 },
    { name: 'q', code: 'DE_Q', keys: 'q' },
    { name: 'w', code: 'DE_W', keys: 'w' },
    { name: 'e', code: 'DE_E', keys: 'e' },
    { name: 'r', code: 'DE_R', keys: 'r' },
    { name: 't', code: 'DE_T', keys: 't' },
    { name: 'z', code: 'DE_Z', keys: 'z' },
    { name: 'u', code: 'DE_U', keys: 'u' },
    { name: 'i', code: 'DE_I', keys: 'i' },
    { name: 'o', code: 'DE_O', keys: 'o' },
    { name: 'p', code: 'DE_P', keys: 'p' },
    { name: 'ü', code: 'DE_UDIA', keys: 'ü' },
    { name: '+\n+~', code: 'DE_PLUS', keys: '+' },
    { width: 1500 },
    { width: 250 },
    { name: 'Delete', code: 'KC_DEL', keys: 'delete' },
    { name: 'End', code: 'KC_END', keys: 'end' },
    { name: 'Page Down', code: 'KC_PGDN', keys: 'pagedown' },
    { width: 250 },
    { name: '7', code: 'KC_P7', keys: 'num_7' },
    { name: '8', code: 'KC_P8', keys: 'num_8' },
    { name: '9', code: 'KC_P9', keys: 'num_9' },
    { name: '+', code: 'KC_PPLS', keys: 'num_add' },
    { width: 0 },

    { name: 'Caps Lock', code: 'KC_CAPS', keys: 'caps_lock', width: 1750 },
    { name: 'a', code: 'DE_A', keys: 'a' },
    { name: 's', code: 'DE_S', keys: 's' },
    { name: 'd', code: 'DE_D', keys: 'd' },
    { name: 'f', code: 'DE_F', keys: 'f' },
    { name: 'g', code: 'DE_G', keys: 'g' },
    { name: 'h', code: 'DE_H', keys: 'h' },
    { name: 'j', code: 'DE_J', keys: 'j' },
    { name: 'k', code: 'DE_K', keys: 'k' },
    { name: 'l', code: 'DE_L', keys: 'l' },
    { name: 'ö', code: 'DE_ODIA', keys: 'ö' },
    { name: "ä", code: 'DE_ADIA', keys: "ä" },
    { name: '\'\n#', code: 'DE_HASH', keys: '#' },
    { width: 1250 },
    {
        name: 'Enter',
        code: 'KC_ENT',
        keys: 'enter',
        classes: 'isoenter',
        width: 1250
    },
    { width: 3500 },
    { name: '4', code: 'KC_P4', keys: 'num_4' },
    { name: '5', code: 'KC_P5', keys: 'num_5' },
    { name: '6', code: 'KC_P6', keys: 'num_6' },
    { name: ',', code: 'KC_PCMM' },
    { width: 0 },

    { name: 'Left Shift', code: 'KC_LSFT', keys: 'shift', width: 1250 },
    { name: '>\n<|', code: 'DE_LABK', keys: '<' },
    { name: 'y', code: 'DE_Y', keys: 'y' },
    { name: 'x', code: 'DE_X', keys: 'x' },
    { name: 'c', code: 'DE_C', keys: 'c' },
    { name: 'v', code: 'DE_V', keys: 'v' },
    { name: 'b', code: 'DE_B', keys: 'b' },
    { name: 'n', code: 'DE_N', keys: 'n' },
    { name: 'm', code: 'DE_M', keys: 'm' },
    { name: ';\n,', code: 'DE_COMM', keys: ',' },
    { name: ':\n.', code: 'DE_DOT', keys: '.' },
    { name: '_\n-', code: 'DE_MINS', keys: '-' },
    { name: 'Right Shift', code: 'KC_RSFT', width: 2000 },
    { width: 1250 },
    { name: 'Up', code: 'KC_UP', keys: 'up' },
    { width: 1250 },
    { name: '1', code: 'KC_P1', keys: 'num_1' },
    { name: '2', code: 'KC_P2', keys: 'num_2' },
    { name: '3', code: 'KC_P3', keys: 'num_3' },
    { name: '=', code: 'KC_PEQL' },
    { width: 0 },

    { name: 'Left Ctrl', code: 'KC_LCTL', keys: 'ctrl', width: 1250 },
    { name: 'Left OS', code: 'KC_LGUI', keys: 'cmd', width: 1250 },
    { name: 'Left Alt', code: 'KC_LALT', keys: 'alt', width: 1250 },
    { name: 'Space', code: 'KC_SPC', keys: 'space', width: 6750 },
    { name: 'Alt Gr', code: 'KC_RALT' },
    { name: 'Right OS', code: 'KC_RGUI', width: 1250 },
    { name: 'Menu', code: 'KC_APP', title: 'Context Menu' },
    { name: 'Right Ctrl', code: 'KC_RCTL', width: 1250 },
    { width: 250 },
    { name: 'Left', code: 'KC_LEFT', keys: 'left' },
    { name: 'Down', code: 'KC_DOWN', keys: 'down' },
    { name: 'Right', code: 'KC_RGHT', keys: 'right' },
    { width: 250 },
    { name: '0', code: 'KC_P0', keys: 'num_0', width: 2000 },
    { name: '.', code: 'KC_PDOT', keys: 'num_decimal' },
    { name: 'Enter', code: 'KC_PENT', keys: 'num_enter' },

    { label: 'Shifted symbols', width: 'label' },

    { name: '°', code: 'DE_DEG ', keys: '°' },
    { name: '!', code: 'DE_EXLM', keys: '!' },
    { name: '"', code: 'DE_DQUO', keys: '"' },
    { name: '§', code: 'DE_SECT', keys: '§' },
    { name: '$', code: 'DE_DLR ', keys: '$' },
    { name: '%', code: 'DE_PERC', keys: '%' },
    { name: '&', code: 'DE_AMPR', keys: '&' },
    { name: '/', code: 'DE_SLSH', keys: '/' },
    { name: '(', code: 'DE_LPRN', keys: '(' },
    { name: ')', code: 'DE_RPRN', keys: ')' },
    { name: '=', code: 'DE_EQL ', keys: '=' },
    { name: '?', code: 'DE_QUES', keys: '?' },
    { name: '`', code: 'DE_GRV', keys: '`' },
    // Row 2
    { name: '*', code: 'DE_ASTR', keys: '*' },
    // Row 3
    { name: '\'', code: 'DE_QUOT', keys: '\'' },
    // Row 4
    { name: '>', code: 'DE_RABK', keys: '>' },
    { name: ';', code: 'DE_SCLN', keys: ';' },
    { name: ':', code: 'DE_COLN', keys: ':' },
    { name: '_', code: 'DE_UNDS', keys: '_' },

    { label: 'AltGr symbols', width: 'label' },
    // Row 1
    { name: '²', code: 'DE_SUP2', keys: '²' },
    { name: '³', code: 'DE_SUP3', keys: '³' },
    { name: '{', code: 'DE_LCBR', keys: '{' },
    { name: '[', code: 'DE_LBRC', keys: '[' },
    { name: ']', code: 'DE_RBRC', keys: ']' },
    { name: '}', code: 'DE_RCBR', keys: '}' },
    { name: '\\', code: 'DE_BSLS', keys: '\\' },
    // Row 2
    { name: '@', code: 'DE_AT', keys: '@' },
    { name: '€', code: 'DE_EURO', keys: '€' },
    { name: '~', code: 'DE_TILD', keys: '~' },
    // Row 4
    { name: '|', code: 'DE_PIPE', keys: '' },
    { name: 'µ', code: 'DE_MICR', keys: '' },
];